name: Database Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - staging
        - production
      migration_direction:
        description: 'Migration direction'
        required: true
        default: 'up'
        type: choice
        options:
        - up
        - down
      dry_run:
        description: 'Dry run (no actual changes)'
        required: false
        default: false
        type: boolean

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: |
          if [ "${{ github.event.inputs.environment }}" == "development" ]; then
            echo "DATABASE_URL=${{ secrets.DEV_DATABASE_URL }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "staging" ]; then
            echo "DATABASE_URL=${{ secrets.STAGING_DATABASE_URL }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "production" ]; then
            echo "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" >> $GITHUB_ENV
          fi

      - name: Validate database connection
        run: |
          npm run db:validate

      - name: Create backup (production only)
        if: github.event.inputs.environment == 'production' && github.event.inputs.migration_direction == 'up'
        run: |
          npm run db:backup

      - name: Run migration (dry run)
        if: github.event.inputs.dry_run == 'true'
        run: |
          npm run migrate:${{ github.event.inputs.migration_direction }} -- --dry-run

      - name: Run migration
        if: github.event.inputs.dry_run == 'false'
        run: |
          npm run migrate:${{ github.event.inputs.migration_direction }}

      - name: Verify migration
        if: github.event.inputs.dry_run == 'false'
        run: |
          npm run db:verify

      - name: Notify team
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#database'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          text: |
            Database migration completed for ${{ github.event.inputs.environment }}
            Direction: ${{ github.event.inputs.migration_direction }}
            Dry run: ${{ github.event.inputs.dry_run }}